"""Каталог критериев проверки сайта журнала.

Обязательность (requirement) отделена от результата проверки (status).
"""

from __future__ import annotations

from dataclasses import dataclass
from typing import Literal

Requirement = Literal["required", "conditional", "optional"]
CheckStatus = Literal[
    "missing",
    "formal",
    "partial",
    "complete",
    "conflict",
    "error",
    "not_applicable",
]
AccessModel = Literal[
    "open_access",
    "subscription",
    "hybrid",
    "delayed_open_access",
    "unknown",
]

PAGE_HOME = "/index"
PAGE_POLICIES = "/about/editorialPolicies"
PAGE_TEAM = "/about/editorialTeam"
PAGE_CONTACT = "/about/contact"
PAGE_SPONSORSHIP = "/about/journalSponsorship"
PAGE_SUBMISSIONS = "/about/submissions"
PAGE_SUBSCRIPTIONS = "/about/subscriptions"
PAGE_HISTORY = "/about/history"

CATEGORY_HOME = "homepage"
CATEGORY_POLICIES = "policies"
CATEGORY_TEAM = "team"
CATEGORY_CONTACT = "contact"
CATEGORY_OWNERSHIP = "ownership"
CATEGORY_SUBMISSIONS = "submissions"
CATEGORY_SUBSCRIPTIONS = "subscriptions"
CATEGORY_HISTORY = "history"
CATEGORY_QUALITY = "quality"

CATEGORY_TITLES: dict[str, str] = {
    CATEGORY_HOME: "Главная страница",
    CATEGORY_POLICIES: "Редакционная политика",
    CATEGORY_TEAM: "Редакция",
    CATEGORY_CONTACT: "Контакты",
    CATEGORY_OWNERSHIP: "Издатель и учредители",
    CATEGORY_SUBMISSIONS: "Для авторов",
    CATEGORY_SUBSCRIPTIONS: "Подписка",
    CATEGORY_HISTORY: "История",
    CATEGORY_QUALITY: "Качество представления",
}

PAGE_TITLES: dict[str, str] = {
    PAGE_HOME: "Главная",
    PAGE_POLICIES: "О журнале → Редакционная политика",
    PAGE_TEAM: "О журнале → Редакция",
    PAGE_CONTACT: "О журнале → Контакты",
    PAGE_SPONSORSHIP: "О журнале → Издатель и учредители",
    PAGE_SUBMISSIONS: "О журнале → Для авторов",
    PAGE_SUBSCRIPTIONS: "О журнале → Подписка",
    PAGE_HISTORY: "О журнале → История",
}


@dataclass(frozen=True, slots=True)
class CriterionSpec:
    id: str
    title: str
    category: str
    page: str
    requirement: Requirement
    critical: bool = False
    condition: str | None = None
    ojs_fragments: tuple[str, ...] = ()
    section_aliases: tuple[str, ...] = ()
    keywords: tuple[str, ...] = ()
    min_chars_formal: int = 20
    min_chars_partial: int = 60
    min_chars_complete: int = 140
    max_score: int = 3
    evaluator: str = "text"  # text | custom id


# --- условия применимости (JournalContext flags) ---
COND_OPEN_ACCESS = "open_access"
COND_HYBRID = "hybrid"
COND_DELAYED_OA = "delayed_open_access"
COND_SUBSCRIPTION_LIKE = "subscription_like"
COND_FEES_CHARGED = "fees_charged"
COND_HAS_WAIVER = "has_waiver"
COND_MEDIA_REGISTERED = "media_registered"
COND_NAME_CHANGED = "name_changed"
COND_ISSN_CHANGED = "issn_changed"
COND_HAS_SPONSORS = "has_sponsors"
COND_HUMAN_RESEARCH = "human_research_scope"
COND_ANIMAL_RESEARCH = "animal_research_scope"
COND_CLINICAL = "clinical_scope"
COND_PATIENT_IMAGES = "patient_images_scope"
COND_HAS_EN = "has_english_locale"
COND_ACCEPTS_ADS = "accepts_ads"
COND_PRINT_AND_ONLINE = "print_and_online"


CRITERIA: tuple[CriterionSpec, ...] = (
    # 1. Главная — обязательные
    CriterionSpec(
        "journal.title",
        "Название журнала",
        CATEGORY_HOME,
        PAGE_HOME,
        "required",
        critical=True,
        evaluator="journal_title",
        max_score=3,
    ),
    CriterionSpec(
        "journal.issn",
        "ISSN",
        CATEGORY_HOME,
        PAGE_HOME,
        "required",
        critical=True,
        evaluator="issn",
        keywords=("issn", "eissn", "e-issn"),
    ),
    CriterionSpec(
        "journal.issn_print_online",
        "ISSN печатной и электронной версий",
        CATEGORY_HOME,
        PAGE_HOME,
        "conditional",
        condition=COND_PRINT_AND_ONLINE,
        evaluator="issn_both",
        keywords=("issn (print)", "issn (online)", "eissn", "печатн", "электронн"),
    ),
    CriterionSpec(
        "journal.description",
        "Краткое описание",
        CATEGORY_HOME,
        PAGE_HOME,
        "required",
        evaluator="description",
        min_chars_complete=120,
        keywords=("журнал", "journal", "исследован", "research"),
    ),
    CriterionSpec(
        "journal.cover",
        "Обложка на главной",
        CATEGORY_HOME,
        PAGE_HOME,
        "required",
        evaluator="cover",
        max_score=3,
    ),
    CriterionSpec(
        "journal.current_issue",
        "Текущий выпуск на главной",
        CATEGORY_HOME,
        PAGE_HOME,
        "required",
        evaluator="current_issue",
        max_score=3,
    ),
    CriterionSpec(
        "journal.language",
        "Языки публикации",
        CATEGORY_QUALITY,
        PAGE_HOME,
        "optional",
        evaluator="language",
        keywords=(
            "язык публикации",
            "языки публикации",
            "language of publication",
            "publication language",
            "languages",
            "русский",
            "english",
            "английский",
        ),
        ojs_fragments=("languages",),
    ),
    CriterionSpec(
        "journal.access_model",
        "Модель доступа",
        CATEGORY_POLICIES,
        PAGE_POLICIES,
        "required",
        critical=True,
        evaluator="access_model",
        keywords=(
            "открытый доступ",
            "open access",
            "подпис",
            "subscription",
            "hybrid",
            "гибрид",
            "эмбарго",
            "embargo",
            "отложенн",
        ),
        ojs_fragments=("openAccessPolicy",),
    ),
    # 1. Редакционная политика — обязательные разделы (структура OJS / заголовки)
    CriterionSpec(
        "policy.aims_scope",
        "Тематика журнала",
        CATEGORY_POLICIES,
        PAGE_POLICIES,
        "required",
        critical=True,
        evaluator="policy_section",
        ojs_fragments=("focusAndScope",),
        section_aliases=(
            "тематика журнала",
            "aims and scope",
            "focus and scope",
            "цели и задачи",
            "about the journal",
        ),
        keywords=("тематик", "scope", "aims", "направленность", "цели журнала"),
    ),
    CriterionSpec(
        "policy.sections",
        "Разделы и направления",
        CATEGORY_POLICIES,
        PAGE_POLICIES,
        "required",
        evaluator="policy_section",
        ojs_fragments=("sectionPolicies",),
        section_aliases=(
            "разделы и направления",
            "sections and directions",
            "journal sections",
            "sections",
            "рубрики",
            "направления журнала",
        ),
        keywords=("раздел", "section", "рубрик", "направлен", "rubric"),
        min_chars_partial=25,
        min_chars_complete=70,
    ),
    CriterionSpec(
        "policy.peer_review",
        "Рецензирование",
        CATEGORY_POLICIES,
        PAGE_POLICIES,
        "required",
        critical=True,
        evaluator="peer_review",
        ojs_fragments=("peerReviewProcess",),
        section_aliases=(
            "рецензирование",
            "peer review",
            "peer review process",
            "процесс рецензирования",
        ),
        keywords=(
            "peer review",
            "рецензирован",
            "двойное слепое",
            "double-blind",
            "single-blind",
            "рецензент",
        ),
    ),
    CriterionSpec(
        "policy.frequency",
        "Периодичность",
        CATEGORY_POLICIES,
        PAGE_POLICIES,
        "required",
        evaluator="policy_section",
        ojs_fragments=("publicationFrequency",),
        section_aliases=("периодичность", "publication frequency", "частота выхода"),
        keywords=("периодичность", "frequency", "issues per year", "выпусков в год", "раз в"),
        min_chars_complete=20,
        min_chars_partial=8,
    ),
    CriterionSpec(
        "policy.access",
        "Политика свободного доступа",
        CATEGORY_POLICIES,
        PAGE_POLICIES,
        "required",
        evaluator="policy_section",
        ojs_fragments=("openAccessPolicy",),
        section_aliases=(
            "политика свободного доступа",
            "open access policy",
            "политика открытого доступа",
            "open access",
        ),
        keywords=("открытый доступ", "open access", "свободный доступ", "cc by", "creative commons"),
    ),
    CriterionSpec(
        "policy.archiving",
        "Архивация",
        CATEGORY_POLICIES,
        PAGE_POLICIES,
        "required",
        critical=True,
        evaluator="policy_section",
        ojs_fragments=("archiving",),
        section_aliases=("архивация", "архивирование", "archiving", "long-term archiving"),
        keywords=("архивир", "archiv", "lockss", "clockss", "долговременн", "preservation"),
    ),
    CriterionSpec(
        "policy.fees",
        "Плата за публикацию",
        CATEGORY_POLICIES,
        PAGE_POLICIES,
        "required",
        critical=True,
        evaluator="fees",
        section_aliases=(
            "плата за публикацию",
            "publication fee",
            "article processing charge",
            "apc",
            "публикационные платежи",
        ),
        keywords=(
            "плата за публикац",
            "article processing",
            "apc",
            "publication fee",
            "не взимается",
            "бесплатн",
            "no fee",
            "free of charge",
            "публикационн",
        ),
    ),
    CriterionSpec(
        "policy.ethics",
        "Этический кодекс журнала",
        CATEGORY_POLICIES,
        PAGE_POLICIES,
        "required",
        critical=True,
        evaluator="policy_section",
        section_aliases=(
            "этический кодекс",
            "publication ethics",
            "публикационная этика",
            "ethics",
            "кодекс этики",
            "code of ethics",
            "journal's code of ethics",
        ),
        keywords=("публикационн", "publication ethics", "этик", "cope", "ethics", "кодекс"),
    ),
    CriterionSpec(
        "policy.indexing",
        "Индексирование",
        CATEGORY_POLICIES,
        PAGE_POLICIES,
        "required",
        evaluator="policy_section",
        section_aliases=(
            "индексирование",
            "indexing",
            "abstracting and indexing",
            "базы данных",
        ),
        keywords=("индексир", "indexing", "scopus", "web of science", "ринц", "elibrary"),
        min_chars_partial=25,
        min_chars_complete=60,
    ),
    CriterionSpec(
        "policy.metadata_oa",
        "Политика открытого доступа к метаданным публикации",
        CATEGORY_POLICIES,
        PAGE_POLICIES,
        "required",
        evaluator="policy_section",
        section_aliases=(
            "метадан",
            "metadata",
            "открытый доступ к метаданным",
            "open access to metadata",
            "metadata open access",
        ),
        keywords=("метадан", "metadata", "open metadata", "открытые метаданные"),
        min_chars_partial=30,
        min_chars_complete=80,
    ),
    CriterionSpec(
        "policy.personal_data",
        "Политика обработки персональных данных",
        CATEGORY_POLICIES,
        PAGE_POLICIES,
        "required",
        evaluator="policy_section",
        section_aliases=(
            "персональных данных",
            "personal data",
            "обработки персональных",
            "политика обработки персональных",
            "privacy policy",
            "конфиденциальност",
            "privacy statement",
        ),
        keywords=("персональн", "personal data", "gdpr", "152-фз", "обработк"),
        min_chars_partial=40,
        min_chars_complete=100,
    ),
    CriterionSpec(
        "policy.ai_generative",
        "Политика использования генеративного ИИ",
        CATEGORY_POLICIES,
        PAGE_POLICIES,
        "required",
        evaluator="policy_section",
        section_aliases=(
            "генеративн",
            "generative ai",
            "искусственного интеллекта",
            "использование ии",
            "chatgpt",
        ),
        keywords=("generative", "искусственн", "chatgpt", "ии", " ai "),
        min_chars_partial=30,
        min_chars_complete=80,
    ),
    CriterionSpec(
        "policy.retraction",
        "Политика ретрагирования статей",
        CATEGORY_POLICIES,
        PAGE_POLICIES,
        "required",
        critical=True,
        evaluator="policy_section",
        section_aliases=(
            "ретрагирован",
            "retraction",
            "отзыв статьи",
            "withdrawal of articles",
        ),
        keywords=("ретракц", "ретрагирован", "отзыв статьи", "retraction", "withdraw"),
    ),
    CriterionSpec(
        "policy.article_types",
        "Типы материалов",
        CATEGORY_POLICIES,
        PAGE_POLICIES,
        "optional",
        keywords=(
            "типы статей",
            "типы материалов",
            "article types",
            "original article",
            "review",
            "обзор",
            "рецензи",
            "сообщен",
        ),
    ),
    CriterionSpec(
        "policy.final_decision",
        "Решение о публикации",
        CATEGORY_POLICIES,
        PAGE_POLICIES,
        "optional",
        keywords=(
            "окончательн",
            "final decision",
            "принимает решение",
            "editor-in-chief decides",
            "главный редактор принимает",
        ),
    ),
    CriterionSpec(
        "policy.authorship",
        "Авторство",
        CATEGORY_POLICIES,
        PAGE_POLICIES,
        "optional",
        keywords=("авторств", "authorship", "criteria for authorship", "критерии авторства"),
    ),
    CriterionSpec(
        "policy.conflict_interest",
        "Конфликт интересов",
        CATEGORY_POLICIES,
        PAGE_POLICIES,
        "optional",
        keywords=("конфликт интересов", "conflict of interest", "competing interest"),
    ),
    CriterionSpec(
        "policy.plagiarism",
        "Плагиат",
        CATEGORY_POLICIES,
        PAGE_POLICIES,
        "optional",
        keywords=("плагиат", "plagiarism", "заимствован", "антиплагиат"),
    ),
    CriterionSpec(
        "policy.duplicate_publication",
        "Повторные публикации",
        CATEGORY_POLICIES,
        PAGE_POLICIES,
        "optional",
        keywords=(
            "повторн",
            "дублирующ",
            "duplicate publication",
            "redundant publication",
            "ранее не опубликован",
        ),
    ),
    CriterionSpec(
        "policy.corrections",
        "Исправления",
        CATEGORY_POLICIES,
        PAGE_POLICIES,
        "optional",
        keywords=(
            "исправлен",
            "correction",
            "corrections",
            "erratum",
            "corrigendum",
            "опечатк",
            "correcting errors",
            "mistake",
            "published errors",
            "errors after publication",
        ),
    ),
    CriterionSpec(
        "policy.complaints_appeals",
        "Жалобы и апелляции",
        CATEGORY_POLICIES,
        PAGE_POLICIES,
        "optional",
        keywords=(
            "жалоб",
            "апелляц",
            "претенз",
            "обжалован",
            "complaint",
            "appeal",
            "grievance",
        ),
    ),
    # 1. Редакция
    CriterionSpec(
        "team.editor_in_chief",
        "Главный редактор",
        CATEGORY_TEAM,
        PAGE_TEAM,
        "required",
        critical=True,
        evaluator="editor_in_chief",
        keywords=("главный редактор", "editor-in-chief", "editor in chief", "глав. редактор"),
    ),
    CriterionSpec(
        "team.editor_in_chief_affiliation",
        "Аффилиация главного редактора",
        CATEGORY_TEAM,
        PAGE_TEAM,
        "required",
        critical=True,
        evaluator="eic_affiliation",
        keywords=("университет", "university", "институт", "institute", "аффилиац"),
    ),
    CriterionSpec(
        "team.deputy_editors",
        "Заместители главного редактора",
        CATEGORY_TEAM,
        PAGE_TEAM,
        "required",
        evaluator="deputy_editors",
        keywords=("заместитель", "deputy editor", "associate editor-in-chief"),
    ),
    CriterionSpec(
        "team.editorial_board",
        "Редакционная коллегия",
        CATEGORY_TEAM,
        PAGE_TEAM,
        "required",
        critical=True,
        evaluator="editorial_board",
        keywords=("редакционная коллегия", "editorial board", "editors", "редакторы"),
    ),
    CriterionSpec(
        "team.member_affiliations",
        "Аффилиации членов редколлегии",
        CATEGORY_TEAM,
        PAGE_TEAM,
        "required",
        critical=True,
        evaluator="member_affiliations",
        keywords=("университет", "university", "affiliation", "аффилиац", "институт"),
    ),
    # 1. Контакты — карта и контактные лица
    CriterionSpec(
        "contact.map",
        "Карта",
        CATEGORY_CONTACT,
        PAGE_CONTACT,
        "required",
        critical=True,
        evaluator="contact_map",
        keywords=("google.com/maps", "yandex", "2gis", "карта", "map"),
    ),
    CriterionSpec(
        "contact.persons",
        "Контактные лица",
        CATEGORY_CONTACT,
        PAGE_CONTACT,
        "required",
        critical=True,
        evaluator="contact_persons",
        keywords=(
            "редактор",
            "editor",
            "телефон",
            "phone",
            "email",
            "principal contact",
            "редакция",
        ),
    ),
    CriterionSpec(
        "contact.email",
        "E-mail редакции",
        CATEGORY_CONTACT,
        PAGE_CONTACT,
        "optional",
        evaluator="contact_email",
    ),
    CriterionSpec(
        "contact.address",
        "Адрес редакции",
        CATEGORY_CONTACT,
        PAGE_CONTACT,
        "optional",
        evaluator="contact_address",
        keywords=("адрес", "address", "mailing", "почтовый"),
    ),
    CriterionSpec(
        "contact.editorial_office",
        "Наименование редакции",
        CATEGORY_CONTACT,
        PAGE_CONTACT,
        "optional",
        keywords=("редакц", "editorial office", "principal contact", "основной контакт"),
    ),
    # 1. Издатель / учредитель
    CriterionSpec(
        "ownership.publisher",
        "Издатель",
        CATEGORY_OWNERSHIP,
        PAGE_SPONSORSHIP,
        "required",
        critical=True,
        keywords=("издател", "publisher", "published by"),
    ),
    CriterionSpec(
        "ownership.founder",
        "Учредитель",
        CATEGORY_OWNERSHIP,
        PAGE_SPONSORSHIP,
        "required",
        critical=True,
        evaluator="founder",
        keywords=("учредител", "founder", "founders"),
    ),
    CriterionSpec(
        "ownership.responsibility",
        "Ответственная организация",
        CATEGORY_OWNERSHIP,
        PAGE_SPONSORSHIP,
        "required",
        evaluator="responsibility",
        keywords=("ответственн", "responsible", "sponsor", "издается", "издател", "publisher"),
    ),
    # 1. Для авторов — обязательные разделы страницы /about/submissions
    CriterionSpec(
        "submission.receiving",
        "Прием статей",
        CATEGORY_SUBMISSIONS,
        PAGE_SUBMISSIONS,
        "required",
        critical=True,
        evaluator="policy_section",
        section_aliases=(
            "прием статей",
            "приём статей",
            "submissions",
            "article submission",
            "подача рукописей",
        ),
        keywords=("прием", "подача", "submission", "рукопис"),
        min_chars_partial=20,
        min_chars_complete=80,
    ),
    CriterionSpec(
        "submission.online",
        "Отправка статей",
        CATEGORY_SUBMISSIONS,
        PAGE_SUBMISSIONS,
        "required",
        critical=True,
        evaluator="policy_section",
        ojs_fragments=("onlineSubmissions",),
        section_aliases=(
            "отправка статей",
            "online submissions",
            "online submission",
            "электронная подача",
        ),
        keywords=(
            "подача",
            "submission",
            "login",
            "registration",
            "online",
            "платформ",
        ),
        min_chars_partial=40,
    ),
    CriterionSpec(
        "submission.guidelines",
        "Правила для авторов",
        CATEGORY_SUBMISSIONS,
        PAGE_SUBMISSIONS,
        "required",
        critical=True,
        evaluator="policy_section",
        ojs_fragments=("authorGuidelines",),
        section_aliases=(
            "правила для авторов",
            "author guidelines",
            "руководство для авторов",
            "instructions for authors",
        ),
        keywords=("правила для авторов", "author guidelines", "руководств", "manuscript"),
        min_chars_complete=200,
        min_chars_partial=80,
    ),
    CriterionSpec(
        "submission.copyright",
        "Авторские права",
        CATEGORY_SUBMISSIONS,
        PAGE_SUBMISSIONS,
        "required",
        critical=True,
        evaluator="policy_section",
        ojs_fragments=("copyrightNotice",),
        section_aliases=(
            "авторские права",
            "copyright notice",
            "copyright",
            "уведомление об авторских правах",
        ),
        keywords=("авторск", "copyright", "лиценз", "license", "права"),
        min_chars_partial=60,
    ),
    CriterionSpec(
        "submission.privacy",
        "Конфиденциальность",
        CATEGORY_SUBMISSIONS,
        PAGE_SUBMISSIONS,
        "required",
        critical=True,
        evaluator="policy_section",
        ojs_fragments=("privacyStatement",),
        section_aliases=(
            "конфиденциальность",
            "privacy statement",
            "privacy policy",
            "политика конфиденциальности",
        ),
        keywords=("конфиденциальн", "privacy", "персональн", "данных"),
        min_chars_partial=40,
    ),
    CriterionSpec(
        "submission.article_structure",
        "Структура рукописи",
        CATEGORY_SUBMISSIONS,
        PAGE_SUBMISSIONS,
        "optional",
        keywords=(
            "структура",
            "аннотац",
            "abstract",
            "ключевые слова",
            "keywords",
            "introduction",
            "введен",
        ),
    ),
    CriterionSpec(
        "submission.references",
        "Список литературы",
        CATEGORY_SUBMISSIONS,
        PAGE_SUBMISSIONS,
        "optional",
        keywords=("список литературы", "references", "bibliography", "цитирован", "gost", "vancouver"),
    ),
    CriterionSpec(
        "submission.author_information",
        "Сведения об авторах",
        CATEGORY_SUBMISSIONS,
        PAGE_SUBMISSIONS,
        "optional",
        keywords=("сведения об авторах", "author information", "аффилиац", "affiliation", "orcid"),
    ),
    CriterionSpec(
        "submission.declarations",
        "Декларации",
        CATEGORY_SUBMISSIONS,
        PAGE_SUBMISSIONS,
        "optional",
        keywords=(
            "декларац",
            "declaration",
            "конфликт интересов",
            "финансирован",
            "funding",
            "conflict of interest",
        ),
    ),
    # 2. Условные
    CriterionSpec(
        "policy.license",
        "Лицензия открытого доступа",
        CATEGORY_POLICIES,
        PAGE_POLICIES,
        "conditional",
        condition=COND_OPEN_ACCESS,
        keywords=("cc by", "creative commons", "лиценз", "license", "cc-by"),
    ),
    CriterionSpec(
        "policy.reuse_terms",
        "Условия повторного использования",
        CATEGORY_POLICIES,
        PAGE_POLICIES,
        "conditional",
        condition=COND_OPEN_ACCESS,
        keywords=("повторн", "reuse", "переиздан", "распространять", "share", "адаптир"),
    ),
    CriterionSpec(
        "policy.hybrid_oa_terms",
        "Условия открытой публикации отдельных статей",
        CATEGORY_POLICIES,
        PAGE_POLICIES,
        "conditional",
        condition=COND_HYBRID,
        keywords=(
            "hybrid open access",
            "hybrid journal",
            "гибридный журнал",
            "гибридная модель",
            "open access option",
            "открытая публикация статьи",
        ),
    ),
    CriterionSpec(
        "policy.embargo_period",
        "Срок эмбарго",
        CATEGORY_POLICIES,
        PAGE_POLICIES,
        "conditional",
        condition=COND_DELAYED_OA,
        keywords=("эмбарго", "embargo", "месяц", "month", "отложенн"),
        min_chars_complete=15,
    ),
    CriterionSpec(
        "subscription.method",
        "Порядок оформления подписки",
        CATEGORY_SUBSCRIPTIONS,
        PAGE_SUBSCRIPTIONS,
        "conditional",
        condition=COND_SUBSCRIPTION_LIKE,
        keywords=("подписк", "subscription", "оформить", "subscribe", "агентств"),
    ),
    CriterionSpec(
        "subscription.agency",
        "Подписное агентство или контакт",
        CATEGORY_SUBSCRIPTIONS,
        PAGE_SUBSCRIPTIONS,
        "conditional",
        condition=COND_SUBSCRIPTION_LIKE,
        keywords=("агентств", "agency", "подписн", "contact for subscription"),
    ),
    CriterionSpec(
        "policy.fee_amounts",
        "Размер и виды платежей",
        CATEGORY_POLICIES,
        PAGE_POLICIES,
        "conditional",
        condition=COND_FEES_CHARGED,
        keywords=("руб", "usd", "eur", "apc", "размер платы", "fee amount", "стоимость"),
    ),
    CriterionSpec(
        "policy.fee_waiver",
        "Условия льготы / освобождения от оплаты",
        CATEGORY_POLICIES,
        PAGE_POLICIES,
        "conditional",
        condition=COND_HAS_WAIVER,
        keywords=("waiver", "льгот", "освобожден", "discount", "скидк"),
    ),
    CriterionSpec(
        "journal.media_certificate",
        "Свидетельство о регистрации СМИ",
        CATEGORY_HOME,
        PAGE_HOME,
        "conditional",
        condition=COND_MEDIA_REGISTERED,
        keywords=("свидетельств", "сми", "роскомнадзор", "mass media", "registration certificate"),
    ),
    CriterionSpec(
        "history.previous_title",
        "Предыдущее название",
        CATEGORY_HISTORY,
        PAGE_HISTORY,
        "conditional",
        condition=COND_NAME_CHANGED,
        keywords=("ранее называл", "formerly", "previous title", "прежнее название"),
    ),
    CriterionSpec(
        "history.previous_issn",
        "Предыдущий ISSN и преемственность",
        CATEGORY_HISTORY,
        PAGE_HISTORY,
        "conditional",
        condition=COND_ISSN_CHANGED,
        keywords=("прежний issn", "former issn", "continues", "преемственн"),
    ),
    CriterionSpec(
        "ownership.sponsors",
        "Спонсоры",
        CATEGORY_OWNERSHIP,
        PAGE_SPONSORSHIP,
        "conditional",
        condition=COND_HAS_SPONSORS,
        keywords=("спонсор", "sponsor", "поддерж", "supported by"),
    ),
    CriterionSpec(
        "policy.human_research",
        "Этическое одобрение исследований с людьми",
        CATEGORY_POLICIES,
        PAGE_POLICIES,
        "conditional",
        condition=COND_HUMAN_RESEARCH,
        keywords=(
            "informed consent",
            "информированн",
            "ethics committee",
            "этическ",
            "human subjects",
            "участниками",
        ),
    ),
    CriterionSpec(
        "policy.animal_research",
        "Требования к исследованиям на животных",
        CATEGORY_POLICIES,
        PAGE_POLICIES,
        "conditional",
        condition=COND_ANIMAL_RESEARCH,
        keywords=("animal", "животн", "лабораторн", "iacuc", "эксперимент на"),
    ),
    CriterionSpec(
        "policy.clinical_trials",
        "Регистрация клинических исследований",
        CATEGORY_POLICIES,
        PAGE_POLICIES,
        "conditional",
        condition=COND_CLINICAL,
        keywords=("clinical trial", "клиническ", "clinicaltrials", "регистрац исслед"),
    ),
    CriterionSpec(
        "policy.patient_consent",
        "Согласие на публикацию изображений пациентов",
        CATEGORY_POLICIES,
        PAGE_POLICIES,
        "conditional",
        condition=COND_PATIENT_IMAGES,
        keywords=("patient consent", "согласие пациента", "изображен", "clinical case"),
    ),
    CriterionSpec(
        "locale.english_core",
        "Английский вариант основных сведений",
        CATEGORY_QUALITY,
        PAGE_HOME,
        "conditional",
        condition=COND_HAS_EN,
        evaluator="english_locale",
        keywords=("english",),
    ),
    CriterionSpec(
        "policy.advertising",
        "Рекламная политика",
        CATEGORY_POLICIES,
        PAGE_POLICIES,
        "conditional",
        condition=COND_ACCEPTS_ADS,
        keywords=("реклам", "advertis", "marketing policy"),
    ),
    # 3. Дополнительные (качество)
    CriterionSpec(
        "quality.logo",
        "Логотип журнала",
        CATEGORY_QUALITY,
        PAGE_HOME,
        "optional",
        keywords=("logo", "логотип"),
    ),
    CriterionSpec(
        "quality.founded_year",
        "Год основания",
        CATEGORY_QUALITY,
        PAGE_HOME,
        "optional",
        keywords=("основан", "founded", "since", "год основания", "established"),
    ),
    CriterionSpec(
        "quality.audience",
        "Целевая аудитория",
        CATEGORY_QUALITY,
        PAGE_POLICIES,
        "optional",
        keywords=("аудитор", "audience", "читател", "для кого"),
    ),
    CriterionSpec(
        "quality.history_brief",
        "Краткая история",
        CATEGORY_QUALITY,
        PAGE_HISTORY,
        "optional",
        keywords=("истори", "history", "основан"),
    ),
    CriterionSpec(
        "quality.indexing",
        "Список баз индексирования",
        CATEGORY_QUALITY,
        PAGE_HOME,
        "optional",
        keywords=("индексир", "indexing", "scopus", "wos", "ркнц", "elibrary", "doaj"),
    ),
    CriterionSpec(
        "quality.social",
        "Ссылки на социальные сети",
        CATEGORY_QUALITY,
        PAGE_HOME,
        "optional",
        keywords=("vk.com", "telegram", "facebook", "twitter", "x.com", "youtube"),
    ),
    CriterionSpec(
        "quality.news",
        "Новости журнала",
        CATEGORY_QUALITY,
        PAGE_HOME,
        "optional",
        keywords=("новост", "announcement", "news"),
    ),
    CriterionSpec(
        "quality.deputy_editor",
        "Заместитель главного редактора",
        CATEGORY_QUALITY,
        PAGE_TEAM,
        "optional",
        keywords=("заместитель", "deputy editor", "associate editor"),
    ),
    CriterionSpec(
        "quality.managing_editor",
        "Управляющий редактор / ответственный секретарь",
        CATEGORY_QUALITY,
        PAGE_TEAM,
        "optional",
        keywords=("управляющий редактор", "managing editor", "ответственный секретарь"),
    ),
    CriterionSpec(
        "quality.orcid_team",
        "ORCID членов редколлегии",
        CATEGORY_QUALITY,
        PAGE_TEAM,
        "optional",
        keywords=("orcid",),
        min_chars_complete=16,
    ),
    CriterionSpec(
        "quality.contact_phone",
        "Телефон редакции",
        CATEGORY_QUALITY,
        PAGE_CONTACT,
        "optional",
        keywords=("телефон", "phone", "тел.", "+7"),
    ),
    CriterionSpec(
        "quality.contact_person",
        "Контактное лицо",
        CATEGORY_QUALITY,
        PAGE_CONTACT,
        "optional",
        keywords=("контактное лицо", "contact person", "principal contact"),
    ),
    CriterionSpec(
        "quality.reviewer_count",
        "Количество рецензентов",
        CATEGORY_QUALITY,
        PAGE_POLICIES,
        "optional",
        keywords=("двух рецензент", "two reviewers", "не менее двух", "at least two"),
    ),
    CriterionSpec(
        "quality.review_timeline",
        "Сроки рецензирования",
        CATEGORY_QUALITY,
        PAGE_POLICIES,
        "optional",
        keywords=("срок", "дней", "weeks", "months", "timeline"),
    ),
    CriterionSpec(
        "quality.ai_policy",
        "Политика использования ИИ",
        CATEGORY_QUALITY,
        PAGE_POLICIES,
        "optional",
        keywords=("artificial intelligence", "generative ai", "chatgpt", "генеративн", "ии"),
    ),
    CriterionSpec(
        "quality.file_formats",
        "Допустимые форматы файлов",
        CATEGORY_QUALITY,
        PAGE_SUBMISSIONS,
        "optional",
        keywords=(".doc", ".docx", ".pdf", "формат файла", "file format"),
    ),
    CriterionSpec(
        "quality.manuscript_template",
        "Шаблон рукописи",
        CATEGORY_QUALITY,
        PAGE_SUBMISSIONS,
        "optional",
        keywords=("шаблон", "template", "образец оформлен"),
    ),
)

CRITERIA_BY_ID: dict[str, CriterionSpec] = {c.id: c for c in CRITERIA}

# Страницы, которые checker всегда пытается загрузить
STANDARD_PAGES: tuple[tuple[str, str], ...] = (
    ("homepage", "index"),
    ("about", "about"),
    ("editorialPolicies", "about/editorialPolicies"),
    ("editorialTeam", "about/editorialTeam"),
    ("contact", "about/contact"),
    ("submissions", "about/submissions"),
    ("journalSponsorship", "about/journalSponsorship"),
    ("subscriptions", "about/subscriptions"),
    ("history", "about/history"),
)

PAGE_KEY_BY_PATH: dict[str, str] = {
    PAGE_HOME: "homepage",
    PAGE_POLICIES: "editorialPolicies",
    PAGE_TEAM: "editorialTeam",
    PAGE_CONTACT: "contact",
    PAGE_SPONSORSHIP: "journalSponsorship",
    PAGE_SUBMISSIONS: "submissions",
    PAGE_SUBSCRIPTIONS: "subscriptions",
    PAGE_HISTORY: "history",
}
